import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    questionText: {
        backgroundColor: 'black',
        color: 'white',
        fontFamily: 'sans-serif',
        fontSize: 22,
        flexWrap: 'nowrap',
        width: '70%',
        height: 'auto',
        textAlign: 'left',
        opacity: 0.7,
        top: '15%',
    },
    questionTextArea: {
        marginTop: 10,
        flex: 0.4,
    },
    questionButton: {
        width: '90%',
        height: 70,
        opacity: 0.7,
        borderColor: 'black',
        borderStyle: 'solid',
        borderRadius: 10,
        borderWidth: 2,
        marginBottom: 10,
        backgroundColor: 'white',
        flex: 1,
        display: 'flex',
        flexDirection: 'row',
    },
    buttonText: {
        textAlign: 'left',
        left: 5,
        top: '1%',
        width: '70%',
        color: 'white',
        textShadowColor: 'black',
        textShadowRadius: 4,
        textShadowOffset: { width: 1, height: 1 },
        flex: 1,
    },
    buttonCorrect: {
        bottom: 20,
        height: 70,
        width: 10,
        flex: 0.3,
    },
    buttonWrongBack: {
        backgroundColor: 'red',
    },
    buttonCorrectBack: {
        backgroundColor: 'green',
    },
    fillerText: {
        flex: 0.5,
    },
    backgroundImage: {
        flex: 8,
        width: '100%',
        flexDirection: 'row',
    },
    forYouHeader: {
        height: '10%',
        display: 'flex',
        flexDirection: 'row',
        paddingTop: '10%',
        flex: 1,
        width: '100%',
    },
    forYouActivity: {},
    forYouTimerContainer: {
        flexDirection: 'row',
        flex: 2,
        height: 24,
        opacity: 0.7,
    },
    forYouTimerText: {
        color: 'white',
        top: 2,
        left: 3,
        fontWeight: 'bold',
    },
    forYouText: {
        flex: 20,
        color: 'white',
        fontSize: 22,
        fontWeight: 'bold',
        height: 25,
        width: '33%',
        textAlign: 'center',
        margin: 0,
        opacity: 1,
    },
    forYouSearch: {
        top: 3,
        right: 3,
        flex: 20,
    },
    questionArea: {
        width: '80%',
        marginLeft: '3%',
        display: 'flex',
        flex: 1,
    },
    questionBottom: {
        paddingTop: 'auto',
        top: '10%',
        flex: 0.4,
    },
    userBottom: {
        top: '10%',
        flex: 0.1,
    },
    usernameText: {
        color: 'white',
        fontWeight: 'bold',
        fontFamily: 'sans-serif',
        fontSize: 15,
    },
    descriptionText: {
        color: 'white',
        fontSize: 12,
    },
    playlistBar: {
        backgroundColor: 'black',
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        flex: 0.5,
    },
    playlistText: {
        color: 'white',
        marginLeft: '3%',
        marginTop: '1%',
        flex: 50,
    },
    playlistChevron: {
        flex: 50,
    },
    questionSideBar: {
        width: '20%',
        top: '70%',
    },
    sidebarAvatar: {
        height: 50,
        width: 50,
        marginBottom: 25,
    },
    sidebarIcon: {
        height: 50,
        width: 50,
        marginBottom: 25,
        alignContent: 'center',
        textAlign: 'center',
        left: 5,
    },
});
